version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: SERVER/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./SERVER:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: CLIENT/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./CLIENT:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # Add this to allow the frontend to communicate with the backend
      - NEXT_PUBLIC_API_URL=http://backend:8000
    restart: unless-stopped
    depends_on:
      - backend
