FROM python:3.11-slim

WORKDIR /app

COPY SERVER/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN pip install prisma

COPY SERVER/ .

RUN prisma generate

EXPOSE 8000

CMD ["prisma", "db", "push"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
